<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1aa7f405e422f19f1c18c7ef94c7311a
{
    public static $prefixLengthsPsr4 = array (
        'r' => 
        array (
            'roduza_helper\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'roduza_helper\\' => 
        array (
            0 => __DIR__ . '/../..' . '/core',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1aa7f405e422f19f1c18c7ef94c7311a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1aa7f405e422f19f1c18c7ef94c7311a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit1aa7f405e422f19f1c18c7ef94c7311a::$classMap;

        }, null, ClassLoader::class);
    }
}
